service: sudoku-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x

functions:
  get-new-game:
    handler: src/getNewGame.handler
    events:
      - httpApi:
          path: /sudoku
          method: get